Running with dbt=1.7.7
Registered adapter: postgres=1.7.7
Found 10 models, 3 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models

Concurrency: 2 threads (target='local')

1 of 5 START sql table model dbt_alice.orders_cleaned .......................... [RUN]
2 of 5 START sql table model dbt_alice.users_cleaned ........................... [RUN]
2 of 5 ERROR creating sql table model dbt_alice.users_cleaned .................. [[31mERROR[0m in 0.05s]
1 of 5 ERROR creating sql table model dbt_alice.orders_cleaned ................. [[31mERROR[0m in 0.05s]
3 of 5 SKIP relation dbt_alice.orders_augmented ................................ [[33mSKIP[0m]
4 of 5 SKIP relation dbt_alice.order_stats ..................................... [[33mSKIP[0m]
5 of 5 SKIP relation dbt_alice.daily_order_summary ............................. [[33mSKIP[0m]

Finished running 5 table models in 0 hours 0 minutes and 0.18 seconds (0.18s).

[31mCompleted with 2 errors and 0 warnings:[0m

  Database Error in model users_cleaned (models/cleaned/users_cleaned.sql)
  relation "raw_data.users" does not exist
  LINE 15: from "dbt"."raw_data"."users"
                ^
  compiled Code at target/dbt_project_assets-1278e48-5157f97/run/dbt_project/models/cleaned/users_cleaned.sql

  Database Error in model orders_cleaned (models/cleaned/orders_cleaned.sql)
  relation "raw_data.orders" does not exist
  LINE 20: from "dbt"."raw_data"."orders"
                ^
  compiled Code at target/dbt_project_assets-1278e48-5157f97/run/dbt_project/models/cleaned/orders_cleaned.sql

Done. PASS=0 WARN=0 ERROR=2 SKIP=3 TOTAL=5
